import "@/styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="/assets/fonts/stylesheet.css" rel="stylesheet" />
      </head>
      <body>{children}</body>
    </html>
  );
}
